#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Wren on Raspberry Pi — one-shot installer
#
# For small settings (childminders / 2-tablet nurseries). Run on a fresh
# 64-bit Raspberry Pi OS (Lite is fine), as a normal user with sudo:
#
#   curl -fsSL <bundle-url>/install-wren-pi.sh | bash
#     — or, from a copy of the bundle folder —
#   bash pi/install-wren-pi.sh
#
# What it does:
#   1. sanity-checks the hardware/OS (arm64, RAM, disk type warning for SD)
#   2. installs Docker (get.docker.com) if missing
#   3. generates .env with strong random secrets (first run only)
#   4. builds + starts Wren (postgres + app) with the Pi resource profile
#   5. prints the tablet URL + first-run login details
# Re-running is safe: existing .env and data volume are never overwritten.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# Preset: `install-wren-pi.sh --childminder` (or WREN_PRESET=childminder in the
# environment/.env) strips the instance to the childminder feature set after
# first boot. Reversible in Roost -> System -> Setup & Features.
PRESET="${WREN_PRESET:-}"
for a in "$@"; do [ "$a" = "--childminder" ] && PRESET=childminder; done

say()  { printf '\033[1;34m[wren-pi]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[wren-pi]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[wren-pi]\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. Sanity checks ─────────────────────────────────────────────────────────
ARCH=$(uname -m)
[ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ] || [ "$ARCH" = "x86_64" ] \
  || die "Unsupported architecture: $ARCH (need 64-bit OS — reflash with Raspberry Pi OS 64-bit)"
[ "$ARCH" = "armv7l" ] && die "32-bit OS detected — reflash with Raspberry Pi OS 64-bit"

RAM_MB=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)
if [ "$RAM_MB" -lt 3500 ]; then
  warn "Only ${RAM_MB}MB RAM detected. Wren needs a 4GB Pi minimum — continuing, but expect swap."
fi

ROOT_DEV=$(findmnt -n -o SOURCE / || true)
case "$ROOT_DEV" in
  /dev/mmcblk*) warn "Running from an SD card. Postgres will wear SD cards out — a USB SSD is strongly recommended for real use." ;;
esac

# ── 2. Docker ────────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker…"
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER"
  warn "Added $USER to the docker group — log out/in (or reboot) if docker commands fail after install."
fi
sudo systemctl enable --now docker >/dev/null 2>&1 || true

# ── 3. Locate the bundle ─────────────────────────────────────────────────────
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)
BUNDLE_DIR=$(dirname "$SCRIPT_DIR")   # pi/ lives inside the eyfs-selfhost bundle
[ -f "$BUNDLE_DIR/docker-compose.yml" ] || die "Can't find docker-compose.yml — run this from inside the wren self-host bundle (pi/install-wren-pi.sh)"
cd "$BUNDLE_DIR"

# ── 4. .env (first run only) ─────────────────────────────────────────────────
if [ ! -f .env ]; then
  say "Generating .env with fresh secrets…"
  PG_PASS=$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 24)
  JWT_SEC=$(head -c 48 /dev/urandom | od -An -tx1 | tr -d ' \n')
  cat > .env <<ENV
# Generated by install-wren-pi.sh on $(date -Iseconds) — edit as needed.
PG_PASSWORD=${PG_PASS}
JWT_SECRET=${JWT_SEC}
PORT=8080
# AI: 'none' (default) hides/degrades AI features. For AI on a Pi use a cloud
# provider: AI_PROVIDER=groq + GROQ_API_KEY=gsk_... (no local models on a Pi).
AI_PROVIDER=none
ENV
  chmod 600 .env
else
  say ".env already exists — keeping it."
fi

# ── 5. Build + start with the Pi profile ─────────────────────────────────────
say "Building Wren (first build on a Pi takes 10-20 minutes — go make a brew)…"
docker compose -f docker-compose.yml -f pi/docker-compose.pi.yml build
say "Starting…"
docker compose -f docker-compose.yml -f pi/docker-compose.pi.yml up -d

# ── 5b. Preset (childminder) ─────────────────────────────────────────────────
if [ "$PRESET" = "childminder" ]; then
  say "Applying the CHILDMINDER preset (waits for the database to come up)…"
  for i in $(seq 1 30); do
    if docker compose -f docker-compose.yml -f pi/docker-compose.pi.yml exec -T db          pg_isready -U wren >/dev/null 2>&1; then break; fi
    sleep 2
  done
  docker compose -f docker-compose.yml -f pi/docker-compose.pi.yml exec -T db     psql -U wren -d wren < pi/preset-childminder.sql     && say "Childminder preset applied — staff/rota, H&S, inspection and AI modules are off."     || warn "Preset could not be applied automatically — run: docker compose exec -T db psql -U wren -d wren < pi/preset-childminder.sql"
fi

# ── 6. Done ──────────────────────────────────────────────────────────────────
IP=$(hostname -I 2>/dev/null | awk '{print $1}')
PORT=$(grep -E '^PORT=' .env | cut -d= -f2)
say ""
say "──────────────────────────────────────────────────────"
say "  Wren is starting at:  http://${IP:-<pi-ip>}:${PORT:-8080}"
say "  Open that URL on the tablets and bookmark/'Add to Home Screen'."
say "  First-run setup (nursery name, rooms, staff PINs) runs in the browser."
say "  Update later:  cd $BUNDLE_DIR && git pull && $0"
say "──────────────────────────────────────────────────────"
